### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by ycchhueannu** [kiankd/events#1]
All .txt files in main.py are not found, like ecb_plus_word_embeddings.txt, 
ecb_plus_ners.txt, and so on. Can you upload the missing files? Thanks.

ps. when I ran "python main.py", it said that "No such file or directory: '../vocab_files/ecb_plus_word_embeddings.txt'"

**Comment by kiankd** [comment]
Hello, they've all been added in the most recent push!

Best,
Kian

**Comment by ycchhueannu** [comment]
ok, thanks.
