### ISSUE TITLE
File(s) missing (all_parsed_ecb+.npy)

### ISSUE THREAD

**Issue by ycchhueannu** [kiankd/events#2]
As title, although there's only one file missing at present, I wonder if all the files under "npy_data" should be uploaded.
After checking simple_helpers.py, I also found that "conll_corefs" folder not included. Can you upload this as well? Thanks.

Here is the error message:

Traceback (most recent call last):
  File "main.py", line 94, in <module>
    cd = load(events_only=False)
  File "main.py", line 27, in load
    coredocs = Documents.load(events_only=events_only)
  File "/home/cychen/events/python/general_classes.py", line 148, in load
    return np.load(helpers.NPY_DATA_DIR+('events_' if events_only else 'all_')+load_file)[0]
  File "/home/cychen/venv/lib/python3.5/site-packages/numpy/lib/npyio.py", line 384, in load
    fid = open(file, "rb")
  FileNotFoundError: [Errno 2] No such file or directory: '/home/rldata/event_coreference_data/npy_data/all_parsed_ecb+.npy'

**Comment by kiankd** [comment]
The "conll_corefs" folder was renamed to be "results" - please change that as it suits you in the code (or you can rename results to "conll_corefs").

Apologies about the hardcoded directories. After using the startup script you can use main.py & extract_ecbplus.py to construct the .npy files you will need, using the object structure in general_classes.py. Unfortunately, I wrote this code using the "comment/uncomment design pattern", which isn't very scalable. Best of luck!

**Comment by ycchhueannu** [comment]
ok, it seems that I should not rename the folder "results" since "get_scores.sh" uses the name "results" as well.

However, there's still one problem unsolved previously: "all_parsed_ecb+.npy" missing (should be under npy_data folder)
I can only generate "events_parsed_ecb+.npy", can you help me generate "all_parsed_ecb.npy"? Thanks.

I've tried to set get_all=True in line 12, main.py, but error message said:
  File "main.py", line 83, in <module>
    cd = build(TOPICS, events_only=EVENTS_ONLY)
  File "main.py", line 17, in build
    coredocs.convert(Documents(ecbdoc_list), clusters)
  File "/home/cychen/events/python/general_classes.py", line 108, in convert
    self[key].convert_tokens(ecbdocs[key], clusters.get_mentions_by_doc(ecbdocs[key].fname))
  File "/home/cychen/events/python/corenlp_classes.py", line 67, in convert_tokens
    assert len(tokens) == len(ecbtokens)

ps here are the following steps I have done so far, you can skip if not interested.

0. uncomment the line 81, 82, 83 in main.py
    error message: FileNotFoundError: [Errno 2] No such file or directory: 
    '/home/rldata/event_coreference_data/npy_data/all_parsed_ecb+.npy'

1. change 'rb' to 'r' in line 21, extract_ecbplus.py
    error message: _csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

2. delete ".DS_Store" in "events/ECB+/ECB+" (since line 41 in extract_ecbplus.py, "topic = int(directory)")
    error message: ValueError: invalid literal for int() with base 10: '.DS_Store'

3. modify NPY_DATA_DIR in line 16, simple_helper.py
    error message: 
    File "../python/main.py", line 82, in <module>
      cd.serialize(events_only=EVENTS_ONLY)
    File "/home/cychen/events/python/general_classes.py", line 144, in serialize
      np.save(helpers.NPY_DATA_DIR+('events_' if events_only else 'all_')+save_file, np.array([self]))
    File "/home/cychen/venv/lib/python3.5/site-packages/numpy/lib/npyio.py", line 502, in save
      fid = open(file, "wb")
    FileNotFoundError: [Errno 2] No such file or directory: 
      '/home/rldata/event_coreference_data/npy_data/events_parsed_ecb+.npy'

4. run main.py and get events_parsed_ecb+.npy

**Comment by kiankd** [comment]
Added the files in the latest commit!

You will have to change the directory structure in the code according to your use-case.
