### ISSUE TITLE
typo in README.md

### ISSUE THREAD

**Issue by ycchhueannu** [kiankd/events#3]
*.response.conll should change to *.response_conll
in these two lines:
1. bash get_scores.sh MODEL_NAME.response.conll
2. bash get_scores.sh ecb_plus_events_test_mention_based_WITHINDOC_.key_conll  MODEL_NAME__within.response.conll

**Comment by kiankd** [comment]
Fixed in latest commit

**Comment by ycchhueannu** [comment]
The first line has not changed yet, but I think that's not a big issue tho.
"bash get_scores.sh MODEL_NAME.response.conll"
